#database
spring:

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/note?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
      timeout: 600000
